import Image from "next/image";

export default function PartnerFounder() {
  return <section className="ic-partner-section ic-founder-section" aria-labelledby="partner-founder-title"><p className="ic-eyebrow">WHY VIVIAN</p><h2 id="partner-founder-title">Someone who actually<br/>shows up.</h2><div className="ic-founder-story"><figure className="ic-founder-portrait"><Image src="/vivian-headshot.jpg" alt="Vivian Yang at UC Berkeley" width={1200} height={1801} sizes="(max-width: 850px) 90vw, 300px"/><figcaption>Vivian Yang · Founder</figcaption></figure><div><h3>Community experience.<br/>A product to build on.</h3><p>Vivian is a UC Berkeley mechanical engineering student and product builder. She has launched Walkie Talkie on campus through tabling, partnerships, and social campaigns, and participates in San Francisco’s event scene.</p><p>She’s building Interaction Club’s personal invitations and matching workflow to make meeting people feel more intentional.</p><p>The first gatherings are founder-led. The longer-term plan pairs repeatable formats with local hosts, supported by software for invitations, attendance, and follow-through.</p></div></div></section>;
}

export function CommunityMarketSignals() {
  return <section className="ic-partner-section"><p className="ic-eyebrow">COMMUNITY IS ALREADY A BUSINESS PRIORITY</p><h2>Companies are showing up<br/>in real life, too.</h2><div className="ic-partner-grid"><article className="ic-partner-card"><h3>Claude communities</h3><p>Anthropic supports a global community program with local gatherings.</p><a className="ic-partner-source" href="https://claude.com/community" target="_blank" rel="noopener noreferrer">Claude community ↗</a></article><article className="ic-partner-card"><h3>Outside organizers</h3><p>Lovable supports community-organized hackathons, buildathons, and workshops. Hosts bring their audience and handle the event.</p><a className="ic-partner-source" href="https://lovable.dev/community-events" target="_blank" rel="noopener noreferrer">Lovable community events ↗</a></article><article className="ic-partner-card"><h3>180+ cities</h3><p>Atlassian supports free, user-led meetups around the world.</p><a className="ic-partner-source" href="https://www.atlassian.com/community" target="_blank" rel="noopener noreferrer">Atlassian community ↗</a></article></div><p className="ic-partner-source">Industry examples, not Interaction Club customers or partnerships.</p></section>;
}
