"use client";
import type { ApplicationRecord } from "@/lib/concierge";
import type { MatchPlan } from "@/lib/matching";
import { belongsToCommunity } from "@/lib/communities";
import { baseAreas } from "@/lib/locations";
import { photoGroupingPreference } from "@/lib/photo-consent";

type Props = { plan: MatchPlan; people: ApplicationRecord[]; onChange: (patch: Partial<MatchPlan>) => void };

export default function CommunityScopeControls(props: Props) {
  return <><div className="exp-form"><label>Dinner photo format<select value={props.plan.photoMode || ""} onChange={event => props.onChange({ photoMode: event.target.value as MatchPlan["photoMode"] })}><option value="">Choose explicitly</option><option value="photography">Photography for club social media</option><option value="photo-free">Photo-free dinner</option></select><small>Photo-free availability is limited; this is a grouping constraint, not a hidden priority penalty. No photos or promotional recording at photo-free dinners. Check current preferences before every event.</small></label><details><summary>Current photo preferences ({props.people.length} responses)</summary>{props.people.map(person => <p key={person.id}><strong>{person.fullName}</strong> — {{"photo-free":"Photo-free dinner required",photography:"Photography and club promotional use permitted",confirm:"Permission missing or limited — confirm before photography"}[photoGroupingPreference(person.photoConsent)]}</p>)}</details></div><CommunityControls {...props}/></>;
}

function CommunityControls({ plan, people, onChange }: Props) {
  const organizations = [...new Set(["Mox", "Innovation Intelligence Hackathon", ...people.flatMap(person => (person.affiliations || []).map(value => value === "Other" && person.communityOther ? `Other: ${person.communityOther}` : value))])].filter(value => !["Other", "None / Prefer not to say"].includes(value));
  const shown = plan.organizationFilter ? people.filter(person => belongsToCommunity(person, plan.organizationFilter!)) : people;
  return <div className="exp-form"><label>Event scope<select value={plan.eventScope || ""} onChange={event => onChange({ eventScope: event.target.value as MatchPlan["eventScope"], community: undefined, moxPilotAgreementConfirmed: false })}><option value="community-only">Closed community dinner</option><option value="cross-community">Wider Interaction Club (opt-in only)</option></select></label>{plan.eventScope === "community-only" && <label>Only invite this community<select value={plan.community || ""} onChange={event => onChange({ community: event.target.value, moxPilotAgreementConfirmed: false })}><option value="">Choose a community</option>{organizations.map(value => <option key={value}>{value}</option>)}</select><small>Membership is self-reported. Confirm client eligibility privately before inviting. A referral alone does not qualify.</small></label>}{plan.eventScope === "community-only" && plan.community === "Mox" && <label className="exp-check"><input type="checkbox" checked={plan.moxPilotAgreementConfirmed === true} onChange={event => onChange({ moxPilotAgreementConfirmed: event.target.checked })}/><span>I confirm Mox and Interaction Club have agreed on this organizational pilot.<small>Required before Mox-only matching or invitations. Individual registrations do not activate the pilot. This is an organizer attestation, not payment verification.</small></span></label>}<label>Meeting area<select value={plan.venueArea || "Berkeley"} onChange={event => onChange({ venueArea: event.target.value })}>{baseAreas.map(value => <option key={value}>{value}</option>)}</select></label><label>Organization filter<select value={plan.organizationFilter || ""} onChange={event => onChange({ organizationFilter: event.target.value || undefined })}><option value="">All organizations</option>{organizations.map(value => <option key={value}>{value}</option>)}</select><small>This also limits suggestions; it never overrides the event scope or a guest’s consent.</small></label><details><summary>Private community context ({shown.length} responses)</summary>{shown.map(person => <p key={person.id}><strong>{person.fullName}</strong> — {(person.affiliations || []).join(", ") || "Not recorded"}{person.communityOther ? ` (${person.communityOther})` : ""} · Wider invitations: {person.crossCommunityOptIn === true ? "Yes" : person.crossCommunityOptIn === false ? "No" : "Not recorded"} · Referral source: {person.referralSource || person.invitedBy || "Not recorded"}</p>)}</details><p className="exp-note">Existing dinners retain their original scope. Missing older consent is not a yes; ask before including those guests in wider-community matching.</p></div>;
}
