type ContextKey = "dinnerSideQuest" | "currentRabbitHole" | "tenMinuteTopic" | "meetAgainSpark" | "yapper" | "yapperContext";
type Props = Record<ContextKey, string> & { onChange: (key: ContextKey, value: string) => void };
const quests = ["Bookstore treasure hunt", "Dessert expedition", "Make something tiny", "A scenic walk"];
const sparks = ["We laughed at the same things", "I learned something unexpected", "I felt understood", "We made an actual next plan"];
export default function PersonalityQuestions(props: Props) {
  return <>
    <fieldset><legend>Are you a yapper? <span>optional</span></legend><div className="options">{["Yes — I talk a lot", "No", "Depends on…"].map(choice => <button type="button" key={choice} aria-pressed={props.yapper === choice} className={props.yapper === choice ? "selected" : ""} onClick={() => props.onChange("yapper", props.yapper === choice ? "" : choice)}>{choice}</button>)}</div><label className="compact">Anything that changes your yapper energy? <span>optional</span><textarea rows={3} maxLength={240} value={props.yapperContext} onChange={e => props.onChange("yapperContext", e.target.value)} placeholder="How I’m feeling, who I’m with…"/></label><p className="helper">Your take, not a label or a ranking.</p></fieldset>
    <fieldset><legend>Your dinner table gets one side quest. What are we doing? <span>optional</span></legend><div className="options">{quests.map(choice => <button type="button" key={choice} aria-pressed={props.dinnerSideQuest === choice} className={props.dinnerSideQuest === choice ? "selected" : ""} onClick={() => props.onChange("dinnerSideQuest", props.dinnerSideQuest === choice ? "" : choice)}>{choice}</button>)}</div><label className="compact">Or your own idea<textarea rows={3} maxLength={240} value={props.dinnerSideQuest} onChange={e => props.onChange("dinnerSideQuest", e.target.value)} placeholder="There’s a very specific bakery I need to investigate…"/></label></fieldset>
    <label className="compact">A stranger asks what you’ve been unusually into lately. What rabbit hole are you opening? <span>optional</span><textarea rows={2} maxLength={400} value={props.currentRabbitHole} onChange={e => props.onChange("currentRabbitHole", e.target.value)} placeholder="A niche hobby, a book, a project, an oddly specific obsession…"/></label>
    <label className="compact">Someone mentions your favorite topic. What could you happily talk about for ten minutes? <span>optional</span><textarea rows={2} maxLength={400} value={props.tenMinuteTopic} onChange={e => props.onChange("tenMinuteTopic", e.target.value)} placeholder="No expertise required. What lights you up?"/></label>
    <fieldset><legend>What would make you leave thinking, “Okay, I want to see these people again”? <span>optional</span></legend><div className="options">{sparks.map(choice => <button type="button" key={choice} aria-pressed={props.meetAgainSpark === choice} className={props.meetAgainSpark === choice ? "selected" : ""} onClick={() => props.onChange("meetAgainSpark", props.meetAgainSpark === choice ? "" : choice)}>{choice}</button>)}</div><label className="compact">Or something else<textarea rows={3} maxLength={240} value={props.meetAgainSpark} onChange={e => props.onChange("meetAgainSpark", e.target.value)} placeholder="The moment that would make it worth coming…"/></label></fieldset>
  </>;
}
