import LegalDocument from "../legal-document";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("/privacy", "Privacy Notice | Interaction Club", "What Interaction Club collects, how we use it, and your choices about profiles, invitations, and feedback.");

export default function PrivacyPage() {
  return <LegalDocument current="/privacy" title="Privacy Notice" label="LAUNCH PRIVACY NOTICE" date="October 6, 2026"
    intro="We collect the smallest useful version of information needed to form a possible plan and email you about it."
    sections={[
      { title: "What we collect", body: <><p>Your full name, email, broad base area, month and year of birth, availability, plan preferences, table preferences, optional food/accessibility details, and optional interests and pronouns you provide. Pronouns are for how we address you and possible future dinner place cards if we make them; they are not used to infer gender or match table types.</p></> },
      { title: "Event check-ins and feedback", body: <><p>We store RSVP changes, check-in timestamps, attendance corrections, and cancellation-review requests to manage attendance and the disclosed matching-priority policy. We do not use location tracking for check-in. If you choose to respond, we also store your before-event check-in, event feedback, private concern reports, and follow-up preference. These are linked to your invitation—not anonymous—and available to Interaction organizers, not other attendees. We use them to improve experiences and review concerns, not as public ratings. They stay in the private organizer inbox, separate from the response Sheet. You can ask the organizer who invited you to review or delete your records, including feedback.</p></> },
      { title: "Photo and video choices", body: <><p>The quiz requires explicit Yes or No answers about capture, hackathon presentations/submissions, and public posts promoting Interaction Club. Permission itself is not required; No answers do not affect invitations. We store your selections, the permission-text version, participation-terms acceptance version, and server timestamps with your private intake record and mirror them into the organizer response Sheet. Choices apply to future club events until changed; no selection or missing older records means no permission. Hosts must respect event-specific changes. Email join@interaction.club to change or withdraw choices or request removal from channels we control. Third-party copies may remain. This does not permit sponsor reuse, paid advertising, sale of your image, facial recognition, AI training, or digital replicas.</p></> },
      { title: "How we use it", body: <><p>We use this information to make or communicate a plan, avoid obviously incompatible suggestions, and operate the invite-only launch. We do not sell it or use it for price discrimination.</p></> },
      { title: "Communities and invitation scope", body: <><p>You can optionally share communities or organizations you belong to. These answers stay in the private organizer inbox and response Sheet, separate from your blurb and referral source. They are self-reported, not membership verification. Community-only dinners stay within the named community. We only include you in wider-community matching when you explicitly opt in; missing older answers are not consent. An invitation link such as /mox records where you found us, not your membership. Email join@interaction.club to change these preferences.</p></> },
      { title: "Side-quest invitations", body: <><p>You can optionally share preferred side-quest days and an outing idea. If you opt into side-quest invitations, we may email you about club outings even outside your selected days. Each invitation is optional. Email vivian_yang@berkeley.edu to stop these invitations or change your preferences. Opting out does not remove you from the dinner matching pool.</p></> },
      { title: "What we do not collect", body: <><p>We do not ask for your home address, precise location, identity documents, background-check information, payment details, or private messages.</p></> },
      { title: "Interest suggestions", body: <><p>When the signup form shows the tag-sharing notice, new interest tag names you submit can become searchable suggestions for other visitors. The suggestion catalog contains only tag names, not names, emails, profiles, or who selected a tag. We do not publish older private responses into this catalog. Keep tags about interests, without contact details. You can ask your organizer to remove a tag from suggestions.</p></> },
      { title: "Personal invitation links", body: <><p>If you create a link on /share, your chosen display name appears publicly on its invitation page with your consent. When a guest finishes the quiz, we privately record the invitation link they used to understand referrals. Organizers can count completed signups by link; referrers do not receive other people’s profiles or email addresses. Links are not identity verification and do not affect matching. Your browser remembers your created link locally and the most recently opened invitation for the current session. Ask your organizer to remove your invitation page.</p></> },
      { title: "Sharing and storage", body: <><p>Only the information needed for a plan may be shared with the organizer or relevant group members. Intake records are stored privately for the launch. Ask the organizer who invited you if you want your intake record deleted.</p></> },
    ]} />;
}
