"use client";
import Link from "next/link";
import EventReminders from "../../event-reminders";
import { useEffect, useState } from "react";
import "../../experience.css";
import { eventMotto } from "../../../lib/brand";
import SurveyLink from "./survey-link";
import AttendancePanel, { type GuestAttendance } from "./attendance-panel";
import type { attendancePriority } from "@/lib/attendance";
export type Invite={table:{activity:string;theme?:string;intent?:string;venueName:string;venueArea:string;venueAddress?:string;startsAt:string;endsAt?:string;responseDeadline?:string;cost?:number;costDetails?:string;hosted?:boolean;hostName?:string;hostContactEmail?:string;sponsorDisclosure?:string;dressCode?:string;venueNotes?:string;status:string};member:GuestAttendance;priority?:ReturnType<typeof attendancePriority>};
export default function TableInvitation({params,demoInvitation}:{params:Promise<{token:string}>;demoInvitation?:Invite}){
  const [token,setToken]=useState(""),[invite,setInvite]=useState<Invite|null>(demoInvitation||null),[error,setError]=useState(""),[opened,setOpened]=useState(false);
  useEffect(()=>{if(demoInvitation)return;let active=true;params.then(async({token:value})=>{try{const response=await fetch("/api/table/"+value);const data=await response.json();if(!response.ok)throw new Error(data.error);if(active){setToken(value);setInvite(data);}}catch{if(active)setError("We couldn’t open this invitation. Check the link or try again.");}});return()=>{active=false;};},[params,demoInvitation]);
  const date=(value?:string)=>value?new Date(value).toLocaleString("en-US",{timeZone:"America/Los_Angeles",dateStyle:"medium",timeStyle:"short"})+" PT":"To be confirmed";
  const table=invite?.table;
  return <main className="experience-site invitation-page"><nav className="exp-nav"><Link className="exp-wordmark" href="/">interaction<span>•</span></Link><span>Something to look forward to.</span></nav><section className="exp-invitation-section">{!table?<p role="status">{error||"Your invitation is on its way…"}</p>:<><p className="exp-kicker">{demoInvitation?"SYNTHETIC DEMO · NO REAL EVENT":"A LITTLE HUMAN INTERACTION"}</p><div className="exp-envelope vibe-social"><div className="envelope-fold" aria-hidden="true"/>{!opened?<button className="envelope-cover" onClick={()=>setOpened(true)}><span>AN INVITATION FOR YOU</span><b>{eventMotto(table.activity)}</b><i>Open your invitation ↗</i><small>{table.venueArea} · {date(table.startsAt)}</small></button>:<div className="exp-letter"><p className="letter-dear">Dear you,</p><h3>{eventMotto(table.activity)}</h3><p>{table.intent==="Builder / founder"?"An evening with people building things, from different backgrounds. Bring your curiosity.":"A little time away from the usual routine, with a new group to get to know."}</p>{table.theme&&<p><b>The vibe:</b> {table.theme}</p>}<p className="exp-subtle">The other guests are a surprise. Your invitation never lists their identities.</p><dl className="exp-logistics"><div><dt>When</dt><dd>{date(table.startsAt)}{table.endsAt&&<><br/>Until {date(table.endsAt)}</>}</dd></div><div><dt>Where</dt><dd>{table.venueName}<br/>{table.venueAddress||table.venueArea}</dd></div><div><dt>Full cost per person</dt><dd>{table.cost===undefined?"Your host will confirm":table.cost===0?"Free":"$"+table.cost.toFixed(2)}<br/>{table.costDetails}</dd></div><div><dt>Format</dt><dd>{table.hosted===false?"Self-guided · no guest is assigned to host":table.hostName?"Hosted by "+table.hostName:"Host to be confirmed"}</dd></div><div><dt>Dress</dt><dd>{table.dressCode||"Your host will confirm"}</dd></div><div><dt>RSVP by</dt><dd>{date(table.responseDeadline)}</dd></div></dl>{table.sponsorDisclosure&&<p><b>About this evening:</b> {table.sponsorDisclosure}</p>}{table.venueNotes&&<p><b>Good to know:</b> {table.venueNotes}</p>}<EventReminders/><p className="exp-subtle">Be present, make room for each other, and step away for calls when you need to. Your phone is always available for essential use.</p>{error&&<p className="exp-error" role="alert">{error}</p>}</div>}</div><HostContact email={table.hostContactEmail}/><AttendancePanel token={token} table={table} initialMember={invite.member} initialPriority={invite.priority} demo={!!demoInvitation}/>{!demoInvitation&&<SurveyLink token={token} table={table}/>}</>}</section><footer className="exp-footer"><span>{eventMotto(table?.activity)}</span><nav><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/safety">Safety</Link></nav></footer></main>;
}
import HostContact from "./host-contact";
