const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const code=ts.transpileModule(fs.readFileSync('lib/matching.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const attendanceCode=ts.transpileModule(fs.readFileSync('lib/attendance.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const attendance={};new Function('exports',attendanceCode)(attendance);
const availability={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/availability.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(availability);
const tags={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/interest-tags.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(tags);
const pilotWeek={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/pilot-week.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(pilotWeek);
const hackathon={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/hackathon.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(hackathon);
const communities={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/communities.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(communities);
const photoConsent={};new Function('exports',ts.transpileModule(fs.readFileSync('lib/photo-consent.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(photoConsent);
const container={exports:{}};new Function('exports','require','module',code)(container.exports,name=>name==='./photo-consent'?photoConsent:name==='./communities'?communities:name==='./locations'?{baseAreas:['Berkeley','San Francisco','Oakland','San Jose','Elsewhere in the Bay']}:name==='./hackathon'?hackathon:name==='./pilot-week'?pilotWeek:name==='./attendance'?attendance:name==='./availability'?availability:name==='./interest-tags'?tags:require(name),container);
const {suggestGroups,eligible,groupProblem,planProblem}=container.exports;
const now=new Date('2026-10-05T20:00:00Z');
const plan={activity:'Dinner',intent:'Builder / founder',format:'Inclusive / everyone',slot:'Fri evening',ageBand:'18–22',cost:12,size:4,startsAt:'2026-10-10T01:00:00Z'};
const person=(id,patch={})=>({id,fullName:id,email:id+'@example.com',birthMonth:1,birthYear:2006,agreement:true,baseArea:'Berkeley',intent:'Builder / founder',gender:'Woman',tableFormats:['Inclusive / everyone','50/50 men + women'],activities:['Dinner'],budget:'Under $15',availability:['Fri evening'],interests:['Art'],submittedAt:'2026-10-05T00:00:00Z',pilotWeekAvailability:{...pilotWeek.PILOT_WEEK,available:true,dinnerDates:['2026-10-09']},...patch});
const pool=[person('a'),person('b'),person('c',{gender:'Man'}),person('d',{gender:'Man'})];
const optOut = {version:photoConsent.PHOTO_CONSENT_VERSION,recordedAt:now.toISOString(),capture:false,hackathon:false,publicPosting:false};
const optIn = {...optOut,capture:true,hackathon:true,publicPosting:true};
const optedOutPerson = person('private',{photoConsent:optOut});
assert.equal(photoConsent.photoGroupingPreference(optOut),'photo-free');
assert.equal(photoConsent.photoGroupingPreference({...optIn,version:'2026-10-07-v1',publicPosting:false}),'confirm');
assert.equal(photoConsent.photoGroupingPreference(null),'confirm');
assert(eligible(optedOutPerson,{...plan,photoMode:'photography'},[],now));
assert.equal(eligible(optedOutPerson,{...plan,photoMode:'photo-free'},[],now),'');
assert(eligible(pool[0],{...plan,photoMode:'photography'},[],now),'Unknown consent never grants permission');
assert.equal(eligible(person('yes',{photoConsent:optIn}),{...plan,photoMode:'photography'},[],now),'');
assert(groupProblem([optedOutPerson,...pool.slice(0,3)],plan));
assert.equal(groupProblem([optedOutPerson,...pool.slice(0,3)],{...plan,photoMode:'photo-free'}),'');
assert.deepEqual(optedOutPerson.photoConsent,optOut,'Grouping never rewrites an opt-out');
const closedPlan={...plan,eventScope:'community-only',community:'Mox',venueArea:'San Francisco',moxPilotAgreementConfirmed:true};
assert.equal(planProblem({...closedPlan,moxPilotAgreementConfirmed:undefined},now),communities.MOX_PILOT_BOUNDARY);
assert.throws(()=>suggestGroups(pool,[],{...closedPlan,moxPilotAgreementConfirmed:false},now),/Member registration does not activate/);
assert(eligible(person('pending',{affiliations:['Mox']}),{...closedPlan,moxPilotAgreementConfirmed:undefined},[],now));
const moxPerson=person('mox',{baseArea:'San Francisco',affiliations:['Mox'],crossCommunityOptIn:false});
assert.equal(eligible(moxPerson,closedPlan,[],now),'','Closed community dinner needs affiliation, not wider opt-in');
assert(eligible({...moxPerson,affiliations:[],referralSource:'mox'},closedPlan,[],now),'A /mox referral is not membership');
assert(eligible({...moxPerson,baseArea:'Berkeley'},closedPlan,[],now),'Community matching still respects location');
assert(eligible(moxPerson,{...closedPlan,eventScope:'cross-community'},[],now),'Unchecked cannot move into broader matching');
assert.equal(eligible({...moxPerson,crossCommunityOptIn:true},{...closedPlan,eventScope:'cross-community'},[],now),'');
assert(eligible({...moxPerson,crossCommunityOptIn:undefined},{...closedPlan,eventScope:'cross-community'},[],now),'Legacy unknown is not opted in');
assert(eligible({...moxPerson,crossCommunityOptIn:true},{...closedPlan,eventScope:'cross-community',organizationFilter:'Innovation Intelligence Hackathon'},[],now),'Organization filters cannot bypass affiliation');
assert.deepEqual(communities.cleanCommunityProfile({affiliations:['Mox','Mox','invalid'],crossCommunityOptIn:'true'}),{affiliations:['Mox'],communityOther:'',crossCommunityOptIn:null});
assert.deepEqual(communities.cleanCommunityProfile({affiliations:['Mox','None / Prefer not to say']}).affiliations,['None / Prefer not to say']);
assert(communities.belongsToCommunity({affiliations:['Other'],communityOther:'Book club'},'Other: book club'));
assert(planProblem({...closedPlan,community:''},now));
assert.equal(hackathon.hackathonAffinity([{}, {hackathonGroupOptIn:true}]),0);
assert.equal(hackathon.hackathonAffinity([{hackathonGroupOptIn:true},{hackathonGroupOptIn:true}]),2);
assert.equal(hackathon.hackathonAffinity([{hackathonGroupOptIn:'true'},{hackathonGroupOptIn:true}]),0);
const affinityPool=Array.from({length:8},(_,i)=>person('h'+i,{hackathonGroupOptIn:i%2===1}));
const affinityGroup=suggestGroups(affinityPool,[],plan,now).groups[0];
assert.equal(affinityGroup.memberIds.filter(id=>affinityPool.find(p=>p.id===id).hackathonGroupOptIn).length,4,'Mutual opt-ins group together when compatible');
assert.equal(suggestGroups(affinityPool,[],plan,now).groups.length,2,'Unchecked people remain eligible');
const mixedCasePool = pool.map((p, i) => ({...p, interests: [['ART'], ['art'], ['Art'], ['  aRt  ']][i]}));
assert.equal(suggestGroups(mixedCasePool,[],plan,now).groups[0].score, suggestGroups(pool,[],plan,now).groups[0].score, 'Capitalization and surrounding spaces never change matching scores');
assert.equal(availability.availabilitySlots.length,21);
assert.equal(availability.pilotAvailabilitySlots.length,7);
assert.deepEqual(availability.cleanAvailability(['Fri evening','Fri dinner','Sat afternoon','garbage',null]),['Fri dinner','Sat lunch']);
assert.equal(planProblem({...plan,slot:'Fri dinner'},now),'');
assert.equal(planProblem({...plan,slot:'Mon dinner',startsAt:'2026-10-06T01:00:00Z'},now),'');
assert.equal(planProblem({...plan,slot:'Fri dinner',startsAt:'2026-11-07T02:00:00Z'},now),'');
assert(planProblem({...plan,slot:'Fri breakfast',startsAt:'2026-10-09T16:00:00Z'},now));
assert(planProblem({...plan,slot:'Fri lunch',startsAt:'2026-10-09T20:00:00Z'},now));
assert(planProblem({...plan,slot:'Fri dinner',startsAt:'2026-10-10T04:00:00Z'},now));
assert.equal(eligible(person('new',{availability:['Fri dinner']}),plan,[],now),'');
assert.equal(eligible(person('old'),{...plan,slot:'Fri dinner'},[],now),'');
assert(eligible(person('lunch',{availability:['Fri lunch']}),{...plan,startsAt:'2026-10-17T01:00:00Z'},[],now));
assert.equal(eligible(person('dated',{availability:[]}),plan,[],now),'','Exact dinner selection is sufficient for that date');
assert(eligible(person('dated',{availability:[]}),{...plan,startsAt:'2026-10-17T01:00:00Z'},[],now),'Dated choice does not imply next-week availability');
assert.equal(suggestGroups(pool,[],plan,now).groups.length,1);
assert.equal(suggestGroups(pool,[],{...plan,format:'50/50 men + women'},now).groups.length,1);
assert.equal(suggestGroups(pool.map(p=>({...p,gender:'Woman'})),[],{...plan,format:'50/50 men + women'},now).groups.length,0);
assert.equal(suggestGroups(pool,[],{...plan,cost:15},now).groups.length,0);
assert(eligible(person('x',{intent:undefined}),plan,[],now));
assert(eligible(person('x',{intent:'Chill / social'}),plan,[],now));
assert.equal(eligible(person('x',{intent:'Open to either'}),plan,[],now),'');
assert(eligible(person('x',{birthYear:2010}),plan,[],now));
assert(eligible(person('x',{availability:['Sat evening']}),{...plan,startsAt:'2026-10-17T01:00:00Z'},[],now));
assert(eligible(person('x',{budget:'$100+'}),plan,[],now));
assert(eligible(person('x',{budget:'Free plans only'}),plan,[],now));
assert.equal(eligible(person('x',{gender:null}),plan,[],now),'');
assert(eligible(person('x'),plan,[{status:'invited',startsAt:plan.startsAt,members:[{applicationId:'x',rsvp:'yes'}]}],now));
assert(groupProblem([pool[0],{...pool[1],email:pool[0].email},pool[2],pool[3]],plan));
assert.equal(suggestGroups(pool.map((p,i)=>({...p,doNotRematchIds:i===0?['b']:[]})),[],plan,now).groups.length,0);
assert.deepEqual(suggestGroups(pool,[],plan,now).groups[0].memberIds,suggestGroups(pool.map(p=>({...p,dietaryNeeds:['Peanut allergy'],accessibilityNotes:'Step free'})),[],plan,now).groups[0].memberIds);
assert(planProblem({...plan,slot:'Sat evening'},now));
assert(planProblem({...plan,size:5},now));
assert(planProblem({...plan,startsAt:'2026-10-01T01:00:00Z'},now));
console.log('PASS: intent, age, activity/time, budget, opt-in format, 50/50 composition, existing plans, duplicate people, do-not-rematch, venue-neutral matching, plan validation.');
