// Local-only UI smoke test. Does not submit to any production endpoint.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const output = path.resolve('.review-artifacts');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('http://127.0.0.1:3000');
  assert(!/PRIVATE REVIEW|not a real|simulated|EXAMPLE INVITATION/.test(await page.locator('main').innerText()));
  await page.getByRole('link', { name: /Find your people/ }).last().click();
  await page.getByLabel('Your full name').waitFor();
  assert.equal(new URL(page.url()).pathname, '/join');
  await page.goto('http://127.0.0.1:3000');
  await page.screenshot({ path: path.join(output, 'public-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(output, 'public-mobile.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('http://127.0.0.1:3000/preview');
  await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true });
  await page.getByRole('button', { name: /Open the envelope/ }).click();
  await page.getByRole('button', { name: /Yes, show me/ }).click();
  await page.getByLabel('What should we call you?').fill('Test guest');
  await page.getByRole('button', { name: 'Review the invitation' }).click();
  await page.locator('.exp-error').waitFor();
  await page.getByRole('button', { name: 'Builder / founder', exact: true }).click();
  await page.getByRole('button', { name: 'Friday dinner, 5–9 PM', exact: true }).click();
  await page.getByLabel('I am 18 or older.').check();
  await page.getByRole('button', { name: /Review the invitation/ }).click();
  assert.equal(await page.locator('.exp-guests').count(), 0);
  assert(!/Sample guest|Engineering|Climate/.test(await page.locator('.exp-letter').innerText()));
  await page.getByRole('button', { name: /Save demo interest/ }).click();
  await page.locator('.exp-error').waitFor();
  await page.locator('.exp-check input').check();
  await page.getByRole('button', { name: /Save demo interest/ }).click();
  await page.getByRole('heading', { name: 'Your interest is noted.' }).waitFor();
  await page.getByRole('link', { name: /View the organizer preview/ }).click();
  await page.locator('.host-guest').first().waitFor();
  await page.getByRole('heading', { name: 'Test guest', exact: true }).waitFor();
  assert.equal(await page.locator('.host-guest').count(), 1);
  await page.getByLabel('Example venue').fill('Example test venue');
  await page.getByLabel('Example start time').fill('2026-10-09T18:00');
  await page.getByLabel('Full attendee cost').fill('$0 · simulated food support');
  await page.getByLabel('Demo guest-seat capacity').fill('1');
  await page.getByRole('button', { name: 'Save demo plan' }).click();
  await page.getByRole('status').waitFor();
  await page.goto('http://127.0.0.1:3000/preview');
  await page.getByRole('button', { name: /Open the envelope/ }).click();
  await page.getByRole('button', { name: /Yes, show me/ }).click();
  await page.getByLabel('What should we call you?').fill('Confirmed test');
  await page.getByRole('button', { name: 'Builder / founder', exact: true }).click();
  await page.getByRole('button', { name: 'Friday dinner, 5–9 PM', exact: true }).click();
  await page.getByLabel('I am 18 or older.').check();
  await page.getByRole('button', { name: /Review the invitation/ }).click();
  await page.locator('.exp-check input').check();
  await page.getByRole('button', { name: /Simulate RSVP/ }).click();
  await page.getByRole('heading', { name: 'Your simulated seat is confirmed.' }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: /Open the envelope/ }).click();
  await page.getByRole('button', { name: /Yes, show me/ }).click();
  await page.getByLabel('What should we call you?').fill('Overflow test');
  await page.getByRole('button', { name: 'Builder / founder', exact: true }).click();
  await page.getByRole('button', { name: 'Friday dinner, 5–9 PM', exact: true }).click();
  await page.getByLabel('I am 18 or older.').check();
  await page.getByRole('button', { name: /Review the invitation/ }).click();
  await page.locator('.exp-check input').check();
  await page.getByRole('button', { name: /Simulate RSVP/ }).click();
  await page.getByRole('heading', { name: 'On the demo overflow list.' }).waitFor();
  await page.getByRole('button', { name: /Withdraw demo interest/ }).click();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('interaction-review-v1')));
  assert.equal(stored.guests.find((g) => g.name === 'Overflow test').status, 'declined');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://127.0.0.1:3000/preview');
  await page.evaluate(() => localStorage.removeItem('interaction-review-v1'));
  await page.reload();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name: 'Just good company', exact: true }).click();
  await page.getByRole('button', { name: /Open the envelope/ }).click();
  await page.screenshot({ path: path.join(output, 'mobile-invitation.png'), fullPage: true });
  assert.equal(await page.locator('.confetti').evaluate((el) => getComputedStyle(el).display), 'none');
  assert.deepEqual(errors, []);
  console.log('PASS: validation, no attendee roster/profiles, interest persistence, host plan, simulated RSVP, capacity overflow, withdrawal, mobile width, reduced motion, no browser exceptions.');
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
