import { pageMetadata } from "@/lib/seo";
import PartnerInvitation from "../partner-invitation";
import Link from "next/link";
import { CircleMark } from "../../club-brand";
import "../partners.css";
import PartnerFounder, { CommunityMarketSignals } from "../partner-founder";

export const metadata = pageMetadata("/investors", "Investors | Interaction Club", "The invitation is the product. Explore Interaction Club’s real-world connection thesis, sponsor-funded business model, market signals, and founder pitch deck.");
const deck = "/interaction-club-pitch-deck.pdf";

export default function InvestorsPage() {
  return <div className="ic-partner-page">
    <header className="ic-partner-hero"><div><p className="ic-eyebrow">THE BIGGER INVITATION</p><h1>You’re invited<br/><em>to invest.</em></h1><p>Our bet: the next great social product won’t ask people to scroll longer. It will give them a reason to show up.</p><p>Interaction Club turns interests and availability into personal invitations, small groups, and real-life plans. Brands can help make those experiences happen.</p><div className="ic-partner-actions"><a href={deck} download className="ic-cta">Download the pitch deck ↓</a><Link href="/join" className="ic-partner-link">Try the product ↗</Link></div></div><PartnerInvitation kind="invest"/></header>
    <div className="ic-partner-ribbon"><span>LESS SCROLLING</span><span>MORE SHOWING UP</span><span>A SECOND HANGOUT</span></div>
    <section className="ic-partner-section"><p className="ic-eyebrow">A VERY REAL PROBLEM</p><h2>Connected online.<br/>Missing each other offline.</h2><div className="ic-partner-stats">
      <article className="ic-partner-stat"><strong>29%</strong><p>of U.S. adults ages 18–29 experienced loneliness a lot of the previous day in Gallup’s Q2 2025 data.</p><a href="https://news.gallup.com/poll/694199/u.s.-depression-rate-remains-historically-high.aspx" target="_blank" rel="noopener noreferrer">Gallup · 2025 ↗</a></article>
      <article className="ic-partner-stat"><strong>150 → 40</strong><p>minutes per day spent in person with friends among U.S. ages 15–24, from 2003 to 2020.</p><a href="https://www.hhs.gov/sites/default/files/surgeon-general-social-connection-advisory.pdf" target="_blank" rel="noopener noreferrer">U.S. Surgeon General’s advisory · 2023 ↗</a></article>
      <article className="ic-partner-stat"><strong>1 in 6</strong><p>people worldwide affected by loneliness, according to the WHO Commission on Social Connection.</p><a href="https://www.who.int/news/item/30-06-2025-social-connection-linked-to-improved-heath-and-reduced-risk-of-early-death" target="_blank" rel="noopener noreferrer">WHO · June 2025 ↗</a></article>
      <article className="ic-partner-stat"><strong>95%</strong><p>of young adults in Eventbrite’s study were interested in bringing their online interests into in-person events.</p><a href="https://www.eventbrite.com/blog/press/newsroom/fourth-spaces-bridge-digital-and-physical-worlds/" target="_blank" rel="noopener noreferrer">Eventbrite · 2025 ↗</a></article>
    </div></section>
    <section className="ic-partner-section"><p className="ic-eyebrow">WHY NOW</p><h2>Connection is getting a new playbook.</h2><div className="ic-partner-grid">
      <article className="ic-partner-card"><span className="ic-partner-number">$18M</span><h3>Introductions, not endless profiles.</h3><p>Hinge founder Justin McLeod’s Overtone announced $18 million raised in July 2026 for a curated matchmaking service.</p><a className="ic-partner-source" href="https://overto.ne/press" target="_blank" rel="noopener noreferrer">Overtone announcement ↗</a></article>
      <article className="ic-partner-card"><span className="ic-partner-number">BFF</span><h3>Friendship becomes a category.</h3><p>Bumble acquired Geneva to expand friendship from one-to-one connections into groups, communities, and meeting offline.</p><a className="ic-partner-source" href="https://bumble.com/en-us/the-buzz/bumble-inc-friendship-communities-geneva" target="_blank" rel="noopener noreferrer">Bumble announcement · 2024 ↗</a></article>
      <article className="ic-partner-card"><span className="ic-partner-number">IRL</span><h3>A shared experience beats a feed.</h3><p>Interest-led gatherings make the first conversation easier to start. Our focus is friendship and community, with the plan built into the invitation.</p><Link className="ic-partner-source" href="/philosophy">Our product philosophy ↗</Link></article>
    </div></section>
    <section className="ic-partner-section"><p className="ic-eyebrow">A PRODUCT YOU CAN OPEN</p><h2>Not “find an event.”<br/>“We want you there.”</h2><ol className="ic-partner-steps"><li><b>Get an invitation.</b><p>A personal introduction from someone you know.</p></li><li><b>Tell us about you.</b><p>Interests and social style, alongside availability and budget.</p></li><li><b>Accept an actual plan.</b><p>A group, date, place, and cost that fit.</p></li><li><b>Meet again.</b><p>Private feedback and follow-through. The second hangout is the outcome that matters.</p></li></ol><ul className="ic-partner-proof" aria-label="Built product features"><li>Personalized invitations</li><li>Personality quiz</li><li>Rule-based group suggestions</li><li>RSVP & check-in</li><li>Before / after feedback</li></ul><div className="ic-partner-actions"><Link className="ic-cta" href="/join">Open the working product ↗</Link></div></section>
    <section className="ic-partner-section"><p className="ic-eyebrow">WHO PAYS?</p><h2>Free to find your people.<br/>Paid to bring communities together.</h2><div className="ic-partner-grid"><article className="ic-partner-card"><h3>The buyer.</h3><p>Community, developer-relations, and brand teams that want relevant, opt-in conversations with people—not another anonymous impression.</p></article><article className="ic-partner-card"><h3>The offer.</h3><p>Curated invitations, a thoughtful gathering, and follow-through. A scoped service fee, with food and production costs separated.</p></article><article className="ic-partner-card"><h3>The repeat.</h3><p>The planned revenue engine is recurring community programs. One useful gathering should create a reason for the sponsor and guests to return.</p></article></div></section>
    <section className="ic-partner-section"><p className="ic-eyebrow">HOW THIS GETS BIGGER</p><h2>Local hosts.<br/>A repeatable invitation engine.</h2><p>Start with founder-led gatherings. Turn what works into repeatable formats and host playbooks. Software handles matching, invitations, attendance, and follow-through so each new community doesn’t start from scratch.</p><div className="ic-partner-grid"><article className="ic-partner-card"><h3>Community loop.</h3><p>Good introductions → another hangout → voluntary referrals → more relevant groups.</p></article><article className="ic-partner-card"><h3>Business loop.</h3><p>Relevant experience → useful conversations → measured follow-through → a recurring program.</p></article><article className="ic-partner-card"><h3>Product leverage.</h3><p>Reusable workflows and local hosts let the founder move from arranging every table to building the system behind them.</p></article></div><details><summary>Inside the deck’s scale illustration</summary><p>The deck models 1,000 business customers × two $500 programs a month × 12 months = $12 million in annual service-fee revenue. This is an illustrative scenario, not current revenue or a forecast. Delivery costs and actual pricing determine margins; the model is not a promise of profitability.</p></details></section>
    <CommunityMarketSignals/>
    <section className="ic-partner-section"><p className="ic-eyebrow">WHY A COMPANY BUYS</p><h2>An organizer can run the event.<br/>A community gives people a reason to come.</h2><p>The initial buyer is a community, marketing, or developer-relations team. Interaction Club’s proposed advantage is combining a relevant, opt-in audience with a hosted experience and measurable follow-through. It can complement an internal coordinator rather than replace the role.</p><p>We begin with founder-led gatherings to test that proposition. The growth plan depends on repeat sponsor purchases and hosts who can deliver the experience beyond Vivian’s own attendance. A trusted community, reusable workflows, and consistent delivery are the intended sources of leverage.</p><p className="ic-partner-source">What we will measure: attendance, relevant product engagement or feedback, consented follow-up, sponsor reorders, and delivery cost per gathering.</p></section>
    <PartnerFounder/>
    <section className="ic-partner-section"><p className="ic-eyebrow">THE NEXT PROOF POINTS</p><h2>One great table.<br/>A reason to come back.</h2><ul className="ic-partner-proof"><li>Invited → attended</li><li>Repeat attendance</li><li>Independent second hangout</li><li>Voluntary referrals</li><li>Sponsor renewal</li></ul><p>Our next chapter is measured in real behavior: people who show up, reconnect, bring a friend, and sponsors who choose to fund another experience.</p></section>
    <aside className="ic-partner-invite"><CircleMark/><p className="ic-eyebrow">PULL UP A CHAIR</p><h2>Back the next reason to get together.</h2><p>Built by Vivian Yang, a UC Berkeley mechanical engineering student and founder who cares about the experience as much as the workflow.</p><div className="ic-partner-actions"><a href={deck} download className="ic-cta">Get the 13-slide deck ↓</a><a className="ic-partner-link" href="mailto:vivian_yang@berkeley.edu">Email Vivian ↗</a><a className="ic-partner-link" href="https://calendly.com/vivian_yang-berkeley/30min" target="_blank" rel="noopener noreferrer">Book a 30-minute chat ↗</a></div><p className="ic-partner-source">Current Canva pitch deck · October 2026 · PDF without presenter notes</p></aside>
  </div>;
}
