"use client";

import Link from "next/link";
import { CSSProperties, FormEvent, useEffect, useState } from "react";
import { emptyPlan, intents, previewKey, slots, type Guest, type Intent, type PreviewPlan } from "@/lib/experience";
import "../experience.css";

type Stage = "invitation" | "preferences" | "group" | "finish";
type Draft = { name: string; intent: Intent | ""; slots: string[]; discipline: string; needs: string; agreement: boolean; adult: boolean };
const freshDraft: Draft = { name: "", intent: "", slots: [], discipline: "", needs: "", agreement: false, adult: false };

export default function Home() {
  const [stage, setStage] = useState<Stage>("invitation");
  const [kind, setKind] = useState<"builder" | "social">("builder");
  const [draft, setDraft] = useState<Draft>(freshDraft);
  const [guests, setGuests] = useState<Guest[]>([]);
  const [plan, setPlan] = useState<PreviewPlan>(emptyPlan);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState("");
  const [progress, setProgress] = useState(0);
  const [outcome, setOutcome] = useState<"interested" | "confirmed" | "overflow">("interested");
  const [myId, setMyId] = useState("");
  const [opened, setOpened] = useState(false);
  const [celebrate, setCelebrate] = useState(false);
  useEffect(() => { if (celebrate) { const timer = setTimeout(() => setCelebrate(false), 1600); return () => clearTimeout(timer); } }, [celebrate]);
  useEffect(() => {
    const hydration = window.requestAnimationFrame(() => {
    try { const saved = localStorage.getItem(previewKey); if (saved) { const data = JSON.parse(saved); if (Array.isArray(data.guests)) setGuests(data.guests); if (data.plan) setPlan(data.plan); } } catch { /* Optional browser-only demo storage. */ }
    setLoaded(true);
    });
    const scroll = () => setProgress(Math.min(1, Math.max(0, window.scrollY / 360)));
    window.addEventListener("scroll", scroll, { passive: true }); return () => { window.cancelAnimationFrame(hydration); window.removeEventListener("scroll", scroll); };
  }, []);
  useEffect(() => { if (loaded) { try { localStorage.setItem(previewKey, JSON.stringify({ guests, plan })); } catch { console.warn("Demo browser storage unavailable."); } } }, [guests, plan, loaded]);
  const confirmedPlan = Boolean(plan.venue.trim() && plan.time && plan.cost.trim() && plan.capacity);
  function navigate(next: Stage) { setError(""); setStage(next); document.getElementById("invitation")?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  function chooseExperience(next: "builder" | "social") { setKind(next); setDraft(freshDraft); setOpened(false); setCelebrate(false); navigate("invitation"); }
  function continuePreferences(event: FormEvent) {
    event.preventDefault();
    if (!draft.name.trim() || !draft.intent || !draft.slots.length || !draft.adult) return setError("Add a name, choose an evening vibe and availability, and confirm you’re 18 or older.");
    navigate("group");
  }
  function saveInterest() {
    if (!draft.agreement || !draft.intent) return setError("Please accept the show-up and safety agreement.");
    const count = guests.filter((g) => g.status === "confirmed").length;
    const status = confirmedPlan ? (count >= (plan.capacity || 0) ? "overflow" : "confirmed") : "interested";
    const id = crypto.randomUUID();
    setGuests([...guests, { id, name: draft.name.trim(), intent: draft.intent, slots: draft.slots, discipline: draft.discipline.trim() || "Curious about different things", status, attended: false, reconnect: false }]);
    setMyId(id); setOutcome(status); navigate("finish");
  }
  return <main className="experience-site">
    <div className="review-banner">PRIVATE REVIEW · example plans and sample guests · no real booking or sponsor</div>
    <nav className="exp-nav"><Link href="/" className="exp-wordmark">interaction<span>•</span></Link><div><a href="#how-it-works">The idea</a><a href="#partners">For partners</a><Link href="/host-preview">Host preview ↗</Link></div></nav>
    <header className="exp-hero"><div className="hero-copy"><p className="exp-kicker">LESS SCROLLING. MORE SHOWING UP.</p><h1>Good people.<br />An actual plan.</h1><p className="exp-tagline">We want you at our table.</p><p className="exp-intro">A small dinner with people you have a reason to meet. A thoughtful invitation, not another feed.</p><a href="#invitation" className="exp-button dark">Open your invitation <span>↗</span></a><span className="exp-subtle">Starting in Berkeley · adults 18+</span></div><div className="exp-art" aria-label="Colorful circles coming together" style={{ "--progress": progress } as CSSProperties}><div className="exp-orbs">{Array.from({ length: 6 }, (_, i) => <i key={i} />)}</div><span>Better together.</span></div></header>
    <section className="exp-how" id="how-it-works"><p className="exp-kicker">A LITTLE INTENTION GOES A LONG WAY</p><div><article><span>01</span><h2>Choose the evening.</h2><p>See the vibe, place, timing, and full cost before you commit. No surprise fee after a quiz.</p></article><article><span>02</span><h2>Find common ground.</h2><p>Shared intent. Different disciplines and perspectives. Availability that actually overlaps.</p></article><article><span>03</span><h2>Make it real.</h2><p>Show up, settle in, and see who you click with. A second hangout matters more than a signup.</p></article></div></section>
    <section className="exp-invitation-section" id="invitation" aria-labelledby="invite-title"><div className="exp-section-heading"><div><p className="exp-kicker">YOU’RE INVITED TO THE IDEA</p><h2 id="invite-title">An evening worth<br />leaving the house for.</h2></div><p>These are example experiences, not live events. Try the whole journey with a made-up name.</p></div>
      <div className="exp-experience-tabs" role="group" aria-label="Dinner experience"><button aria-pressed={kind === "builder"} onClick={() => chooseExperience("builder")}>Builders at the table</button><button aria-pressed={kind === "social"} onClick={() => chooseExperience("social")}>Just good company</button></div>
      <div className={`exp-envelope vibe-${kind} ${opened ? "is-open" : ""}`}><div className="envelope-fold" aria-hidden="true" />{!opened && <button className="envelope-cover" onClick={() => { setOpened(true); if (kind === "social") setCelebrate(true); }}><span>FOR YOU / AN EXAMPLE INVITATION</span><b>{kind === "social" ? "Hello! Come hang out." : "A seat. A conversation. A possibility."}</b><i>Open the envelope ↗</i><small>Example only · Berkeley · date, venue, and cost unconfirmed</small></button>}{celebrate && <div className="confetti" aria-hidden="true">{Array.from({ length: 14 }, (_, i) => <i key={i} style={{ "--i": i } as CSSProperties} />)}{<button onClick={() => setCelebrate(false)} aria-label="Dismiss confetti">×</button>}</div>}<div className="exp-letter" hidden={!opened}><div className="letter-top"><span>BERKELEY / {kind === "builder" ? "BUILDERS" : "SOCIAL"}</span><span className="demo-pill">EXAMPLE INVITATION</span></div><p className="letter-dear">Dear {draft.name.trim() || "you"},</p><h3>{kind === "builder" ? "Bring what you’re building." : "You’re welcome at this table. Yay!"}</h3><p>{kind === "builder" ? "A small, hosted dinner for people making things. Different skills, a shared curiosity, and room to talk beyond your project." : "Good company, something to eat, and no pitch required. Bring your curiosity and your regular self. We’d like to make the first hello a little easier."}</p><dl className="exp-logistics"><div><dt>Where</dt><dd>{plan.venue || "Berkeley · venue not selected"}</dd></div><div><dt>When</dt><dd>{plan.time ? new Date(plan.time).toLocaleString("en-US", { timeZone: "America/Los_Angeles", dateStyle: "medium", timeStyle: "short" }) + " PT" : "Availability first · date not confirmed"}</dd></div><div><dt>Full cost</dt><dd>{plan.cost || "Not confirmed · no payment collected"}</dd></div><div><dt>Your host</dt><dd>Vivian · first pilot</dd></div></dl><p className="exp-note">{plan.funded ? "Simulated sponsor funding in this browser only. No real sponsor exists." : "Food funding is being explored, not promised. Any self-paid option needs a separate yes."} Group size is not settled. Phone-light, with essential and accessibility exceptions.</p>
      {stage === "invitation" && <><div className="letter-actions"><button className="exp-button dark" onClick={() => navigate("preferences")}>Yes, show me how it works ↗</button><button className="exp-text-button" onClick={() => chooseExperience(kind === "builder" ? "social" : "builder")}>Not my vibe · see the other idea</button></div><p className="exp-subtle">Not an RSVP yet. Your preferences come next.</p></>}
      {stage === "preferences" && <form onSubmit={continuePreferences} className="exp-form"><p className="exp-kicker">01 / WHAT WORKS FOR YOU</p><label>What should we call you?<input required maxLength={80} value={draft.name} placeholder="Use a made-up name for this demo" onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><fieldset><legend>What kind of evening do you want?</legend><div className="exp-chips">{intents.map((intent) => <button key={intent} type="button" aria-pressed={draft.intent === intent} onClick={() => setDraft({ ...draft, intent })}>{intent}</button>)}</div><small>Open to either means you’re genuinely comfortable with both. No silent seat-filling.</small></fieldset><fieldset><legend>When can you pull up? Select all.</legend><div className="exp-chips">{slots.map((slot) => <button key={slot} type="button" aria-pressed={draft.slots.includes(slot)} onClick={() => setDraft({ ...draft, slots: draft.slots.includes(slot) ? draft.slots.filter((s) => s !== slot) : [...draft.slots, slot] })}>{slot}</button>)}</div></fieldset><label>What are you into? <small>Optional</small><input value={draft.discipline} maxLength={80} placeholder="Design, engineering, music, climate…" onChange={(e) => setDraft({ ...draft, discipline: e.target.value })} /></label><label>Dietary / accessibility needs <small>Optional · no sensitive details in this demo</small><textarea value={draft.needs} maxLength={240} onChange={(e) => setDraft({ ...draft, needs: e.target.value })} placeholder="We’ll check options, not separate you by allergies." /></label><p className="exp-note">Venue accommodation cannot be guaranteed. Confirm suitability directly before accepting a real plan. These notes stay in this form only and are not saved.</p><label className="exp-check"><input type="checkbox" checked={draft.adult} onChange={(e) => setDraft({ ...draft, adult: e.target.checked })} /> I am 18 or older.</label><div className="letter-actions"><button type="button" className="exp-text-button" onClick={() => navigate("invitation")}>← Back</button><button className="exp-button dark" type="submit">Review the invitation ↗</button></div></form>}
      {stage === "group" && <div className="exp-form"><p className="exp-kicker">02 / YOUR EVENING, NOT A GUEST LIST</p><h4>Leave room for a first hello.</h4><p>You’re choosing the experience. Who you’ll meet stays a surprise until dinner. We use your preferences privately to put together a workable plan—not to showcase individual guests.</p><p className="exp-note">Review the invitation’s vibe, hosted format, place, time, and full cost above. Anything unconfirmed stays unconfirmed; we won’t hide material terms behind the mystery.</p><label className="exp-check"><input type="checkbox" checked={draft.agreement} onChange={(e) => setDraft({ ...draft, agreement: e.target.checked })} /><span>I’ll show up or cancel early, respect the group, and handle any agreed bill directly. Interaction does not background-check or endorse guests. I’ll meet in public and leave if something feels wrong. <Link href="/terms">Terms</Link> · <Link href="/privacy">Privacy</Link> · <Link href="/safety">Safety</Link></span></label><div className="letter-actions"><button className="exp-text-button" onClick={() => navigate("preferences")}>← Edit preferences</button><button className="exp-button dark" disabled={!loaded} onClick={saveInterest}>{confirmedPlan ? "Simulate RSVP" : "Save demo interest"} ↗</button></div></div>}
      {stage === "finish" && <div className="exp-result" role="status"><span className="result-seal">✓</span><p className="exp-kicker">03 / DEMO SAVED, NOT A REAL RESERVATION</p><h4>{outcome === "confirmed" ? "Your simulated seat is confirmed." : outcome === "overflow" ? "On the demo overflow list." : "Your interest is noted."}</h4><p>{outcome === "confirmed" ? "This confirmation exists only in this browser. It is not an actual invitation or booking." : outcome === "overflow" ? "The simulated table is full. You haven’t been charged or moved to a paid plan." : "No dinner is booked. Early interest gets priority only once benefits and seats are confirmed, with a clear response deadline."}</p><p className="exp-note">Demo entries are stored only in this browser. No emails, payments, or notifications are sent.</p><div className="letter-actions"><Link className="exp-button dark" href="/host-preview">View the organizer preview ↗</Link><button className="exp-text-button" onClick={() => { setGuests(guests.map((g) => g.id === myId ? { ...g, status: "declined" } : g)); navigate("invitation"); }}>Withdraw demo interest</button></div></div>}
      {error && <p className="exp-error" role="alert">{error}</p>}
      </div></div>
    </section>
    <section className="exp-future"><p className="exp-kicker">DOWN THE ROAD · NOT LIVE OFFERINGS</p><h2>Same intention.<br />Different kinds of nights.</h2><div><article><span>COMMUNITY</span><h3>Sponsored experiences</h3><p>Free for participants, funded by a partner. Clear purpose, thoughtful hosting, and no surprise sales pitch.</p></article><article><span>OPTIONAL / SELF-PAID</span><h3>The LARP dinner</h3><p>A fancier night, if you’re into it. Full price before you opt in. No promises of status, connections, or better people.</p></article></div><p>Returning reliable, considerate participants may receive priority for future sponsored experiences. Not a public prestige score.</p></section>
    <section className="exp-partners" id="partners"><div><p className="exp-kicker">GIVE YOUR COMMUNITY A REAL-LIFE PLAN</p><h2>Less branded stuff.<br />More shared experiences.</h2><p>Choose one purpose: community relationships, recruiting relationships, or product feedback. We bring together relevant people and handle a thoughtful experience—not just a list of leads.</p></div><div className="partner-card"><h3>The first pilot</h3><p>Food support for one small Berkeley builder dinner. A relevant operator or mentor can join, but a representative isn’t required.</p><ul><li>Agreed budget, payment timing, and cancellation terms</li><li>Tasteful, approved event-specific credit</li><li>Anonymous feedback summary, no automatic contact list</li><li>Disclosed affiliation and planned research or recruiting</li></ul><p className="exp-note">Funding and venue are not confirmed. No guaranteed hires, sales, reach, or attendance. Future pricing must cover coordination costs, not just food.</p></div></section>
    <footer className="exp-footer"><Link href="/" className="exp-wordmark">interaction<span>•</span></Link><p>People first. A plan second. A feed never.</p><nav><Link href="/join">Existing beta signup</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/data">Data</Link><Link href="/safety">Safety</Link></nav></footer>
  </main>;
}
